import { config } from "dotenv";
config();
export default {
  development: {
    MONGODB_URI: process.env.MONGODB_URI,
    MONGODB_DB_MAIN: process.env.MONGODB_DB_MAIN,
    DB_CLIENT: process.env.DB_CLIENT,
    JWT_SECRET: "Dudiya@2302",
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASS: process.env.SMTP_PASS,
    SMTP_SERVICE: process.env.SMTP_SERVICE,
    SWAGGER_API_URL: process.env.BACKEND_URL_DEV,
    FRONTEND_URL: process.env.FRONTEND_URL,
    RAZORPAY_KEY: process.env.RAZORPAY_TEST_KEY,
    RAZORPAY_SECRET_KEY: process.env.RAZORPAY_TEST_SECRET_KEY,
  },
  staging: {
    MONGODB_URI: process.env.MONGODB_URI,
    MONGODB_DB_MAIN: process.env.MONGODB_DB_MAIN,
    DB_CLIENT: process.env.DB_CLIENT,
    JWT_SECRET: "Dudiya@2302",
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASS: process.env.SMTP_PASS,
    SMTP_SERVICE: process.env.SMTP_SERVICE,
    SWAGGER_API_URL: process.env.BACKEND_URL_STAGING,
    FRONTEND_URL: process.env.FRONTEND_URL_STAGING,
    RAZORPAY_KEY: process.env.RAZORPAY_TEST_KEY,
    RAZORPAY_SECRET_KEY: process.env.RAZORPAY_TEST_SECRET_KEY,
  },
  production: {
    MONGODB_URI: process.env.MONGODB_URI,
    MONGODB_DB_MAIN: process.env.MONGODB_DB_PROD,
    DB_CLIENT: process.env.DB_CLIENT,
    JWT_SECRET: "Dudiya@2302",
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASS: process.env.SMTP_PASS,
    SMTP_SERVICE: process.env.SMTP_SERVICE,
    SWAGGER_API_URL: process.env.BACKEND_URL_PROD,
    FRONTEND_URL: process.env.FRONTEND_URL_PROD,
    RAZORPAY_KEY: process.env.RAZORPAY_KEY,
    RAZORPAY_SECRET_KEY: process.env.RAZORPAY_SECRET_KEY,
  },
  test: {
    MONGODB_URI: process.env.MONGODB_URI,
    MONGODB_DB_MAIN: process.env.MONGODB_DB_MAIN,
    DB_CLIENT: process.env.DB_CLIENT,
    timezone: process.env.TIMEZONE,
    dialect: process.env.DIALECT,
  },
}[process.env.NODE_ENV];
